version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - nextjs-app
    networks:
      - quickesta-network
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/quickesta.com.pem:/etc/nginx/quickesta.com.pem
      - ./nginx/quickesta.com.key:/etc/nginx/quickesta.com.key

  nextjs-app:
    build:
      context: .
      dockerfile: nextjs/Dockerfile
    expose:
      - '3002'
    environment:
      - NODE_ENV=production
      - PORT=3002
      - NEXT_PUBLIC_APP_ENV=production
      - NEXT_PUBLIC_SITE_URL=https://dashboard.visa.quickesta.com
      - NEXT_PUBLIC_HASURA_GRAPHQL_URL=${NEXT_PUBLIC_HASURA_GRAPHQL_URL}
      - NEXT_PUBLIC_HASURA_ADMIN_SECRET=${NEXT_PUBLIC_HASURA_ADMIN_SECRET}
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
      - NEXT_PUBLIC_ABANT_API_PROXY=${NEXT_PUBLIC_ABANT_API_PROXY}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    networks:
      - quickesta-network
    restart: always

networks:
  quickesta-network:
    name: quickesta-network
    driver: bridge
